SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT

BALL_RADIUS = 15
BALL_X_VEL = 6

PADDLE_WIDTH = 30
PADDLE_HEIGHT = 130
PADDLE_FORCE = 2

PADDLE_SPEED = 5
PADDLE_SLOW = 1

